---
kind: pipeline
type: docker
name: test-linux-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags
  - name: testing
    image: golang:1.16
    commands:
      - make test

---
kind: pipeline
type: docker
name: build-linux-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build-linux-amd64-artifact
    pull: true
    image: golang:1.16
    commands:
      - export NAME=spiry-$${GOOS}-$${GOARCH}
      - apt-get -q -o=Dpkg::Use-Pty=0 update && apt-get -q -o=Dpkg::Use-Pty=0 install -y bzip2 upx-ucl xz-utils
      - make package NAME=$${NAME}
    environment:
      GOARCH: amd64
      GOOS: linux
    volumes:
      - name: build
        path: /drone/src/build

  - name: flush-to-storage
    image: amazon/aws-cli:latest
    pull: true
    commands:
      - aws configure set default.s3.signature_version s3v4
      - aws --endpoint-url http://192.168.1.10:9000 s3 cp build/*.tar s3://$${AWS_S3_BUCKET}
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_ENDPOINT:
        from_secret: aws_endpoint
      AWS_S3_BUCKET:
        from_secret: aws_s3_bucket
      AWS_DEFAULT_REGION: us-west-1

depends_on:
  - test-linux-amd64

---
kind: pipeline
type: docker
name: build-darwin-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build-darwin-amd64-artifact
    pull: true
    image: golang:1.16
    commands:
      - export NAME=spiry-$${GOOS}-$${GOARCH}
      - apt-get -q -o=Dpkg::Use-Pty=0 update && apt-get -q -o=Dpkg::Use-Pty=0 install -y bzip2 upx-ucl xz-utils
      - make package NAME=$${NAME}
    environment:
      GOARCH: amd64
      GOOS: darwin
    volumes:
      - name: build
        path: /drone/src/build

depends_on:
  - test-linux-amd64

---
kind: pipeline
type: docker
name: build-linux-armv7

platform:
  os: linux
  arch: amd64

steps:
  - name: build-linux-arm64-artifact
    pull: true
    image: golang:1.16
    commands:
      - export NAME=spiry-$${GOOS}-$${GOARCH}
      - apt-get -q -o=Dpkg::Use-Pty=0 update && apt-get -q -o=Dpkg::Use-Pty=0 install -y bzip2 upx-ucl xz-utils
      - make package NAME=$${NAME}
    environment:
      GOARCH: arm
      GOARM: 7
      GOOS: linux
    volumes:
      - name: build
        path: /drone/src/build

depends_on:
  - test-linux-amd64

---
kind: pipeline
type: docker
name: build-darwin-arm64

platform:
  os: linux
  arch: amd64

steps:
  - name: build-darwin-arm64-artifact
    pull: true
    image: golang:1.16
    commands:
      - export NAME=spiry-$${GOOS}-$${GOARCH}
      - apt-get -q -o=Dpkg::Use-Pty=0 update && apt-get -q -o=Dpkg::Use-Pty=0 install -y bzip2 upx-ucl xz-utils
      - make package NAME=$${NAME}
    environment:
      GOARCH: arm64
      GOOS: darwin
    volumes:
      - name: build
        path: /drone/src/build

depends_on:
  - test-linux-amd64

...
