---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: run tests
    image: golang:1.16
    commands:
      - make privileged-tests

  - name: build artifact
    image: golang:1.16
    commands:
      - apt-get update && apt-get install -y upx-ucl
      - make build compress
